project_id = "dihghxkycmllrdednldr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
log_level = "info"
max_header_length = 4096

[storage]
enabled = true
port = 54324
file_size_limit = "50MiB"
public_url = "http://127.0.0.1:54321/storage/v1"

[auth]
enabled = true
port = 54325
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_email_confirmations = false

[auth.email]

[functions.jira-integration]
verify_jwt = false

[functions.generate-test-cases]
verify_jwt = false

[functions.azure-devops-integration]
verify_jwt = false